image: docker:latest

variables:
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - package
  - deploy

package:
  stage: package
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --tag $CI_REGISTRY_IMAGE:${CI_COMMIT_SHA} --tag $CI_REGISTRY_IMAGE:latest -f Dockerfile .
    - docker push $CI_REGISTRY_IMAGE:${CI_COMMIT_SHA}
    - docker push $CI_REGISTRY_IMAGE:latest
  tags:
    - build

deploy:
  stage: deploy
  needs: ["package"]
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest
    - docker stop for-kat-service || true
    - sleep 5
    - docker rm -f for-kat-service || true
    - docker run --name for-kat-service -v /var/run/docker.sock:/var/run/docker.sock -d $CI_REGISTRY_IMAGE:latest
  environment:
    name: prod
  services:
    - docker:dind
  tags:
    - deploy-prod
